/*
EVE Stellar Information (ESI) - tranquility

Testing WarsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package esiclient

import (
	"context"
	"testing"

	openapiclient "github.com/fnt-eve/esi/esiclient"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_esiclient_WarsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WarsAPIService GetWars", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.WarsAPI.GetWars(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WarsAPIService GetWarsWarId", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var warId int64

		resp, httpRes, err := apiClient.WarsAPI.GetWarsWarId(context.Background(), warId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WarsAPIService GetWarsWarIdKillmails", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var warId int64

		resp, httpRes, err := apiClient.WarsAPI.GetWarsWarIdKillmails(context.Background(), warId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
