/*
EVE Stellar Information (ESI) - tranquility

Testing FittingsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package esiclient

import (
	"context"
	"testing"

	openapiclient "github.com/fnt-eve/esi/esiclient"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_esiclient_FittingsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FittingsAPIService DeleteCharactersCharacterIdFittingsFittingId", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var characterId int64
		var fittingId int64

		resp, httpRes, err := apiClient.FittingsAPI.DeleteCharactersCharacterIdFittingsFittingId(context.Background(), characterId, fittingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FittingsAPIService GetCharactersCharacterIdFittings", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var characterId int64

		resp, httpRes, err := apiClient.FittingsAPI.GetCharactersCharacterIdFittings(context.Background(), characterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FittingsAPIService PostCharactersCharacterIdFittings", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var characterId int64

		resp, httpRes, err := apiClient.FittingsAPI.PostCharactersCharacterIdFittings(context.Background(), characterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
