/*
EVE Stellar Information (ESI) - tranquility

Testing WalletAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package esiclient

import (
	"context"
	"testing"

	openapiclient "github.com/fnt-eve/esi/esiclient"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_esiclient_WalletAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WalletAPIService GetCharactersCharacterIdWallet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var characterId int64

		resp, httpRes, err := apiClient.WalletAPI.GetCharactersCharacterIdWallet(context.Background(), characterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WalletAPIService GetCharactersCharacterIdWalletJournal", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var characterId int64

		resp, httpRes, err := apiClient.WalletAPI.GetCharactersCharacterIdWalletJournal(context.Background(), characterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WalletAPIService GetCharactersCharacterIdWalletTransactions", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var characterId int64

		resp, httpRes, err := apiClient.WalletAPI.GetCharactersCharacterIdWalletTransactions(context.Background(), characterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WalletAPIService GetCorporationsCorporationIdWallets", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var corporationId int64

		resp, httpRes, err := apiClient.WalletAPI.GetCorporationsCorporationIdWallets(context.Background(), corporationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WalletAPIService GetCorporationsCorporationIdWalletsDivisionJournal", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var corporationId int64
		var division int64

		resp, httpRes, err := apiClient.WalletAPI.GetCorporationsCorporationIdWalletsDivisionJournal(context.Background(), corporationId, division).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WalletAPIService GetCorporationsCorporationIdWalletsDivisionTransactions", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var corporationId int64
		var division int64

		resp, httpRes, err := apiClient.WalletAPI.GetCorporationsCorporationIdWalletsDivisionTransactions(context.Background(), corporationId, division).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
