/*
EVE Stellar Information (ESI) - tranquility

Testing KillmailsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package esiclient

import (
	"context"
	"testing"

	openapiclient "github.com/fnt-eve/esi/esiclient"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_esiclient_KillmailsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test KillmailsAPIService GetCharactersCharacterIdKillmailsRecent", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var characterId int64

		resp, httpRes, err := apiClient.KillmailsAPI.GetCharactersCharacterIdKillmailsRecent(context.Background(), characterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KillmailsAPIService GetCorporationsCorporationIdKillmailsRecent", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var corporationId int64

		resp, httpRes, err := apiClient.KillmailsAPI.GetCorporationsCorporationIdKillmailsRecent(context.Background(), corporationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KillmailsAPIService GetKillmailsKillmailIdKillmailHash", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var killmailHash string
		var killmailId int64

		resp, httpRes, err := apiClient.KillmailsAPI.GetKillmailsKillmailIdKillmailHash(context.Background(), killmailHash, killmailId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
