/*
EVE Stellar Information (ESI) - tranquility

Testing PlanetaryInteractionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package esiclient

import (
	"context"
	"testing"

	openapiclient "github.com/fnt-eve/esi/esiclient"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_esiclient_PlanetaryInteractionAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PlanetaryInteractionAPIService GetCharactersCharacterIdPlanets", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var characterId int64

		resp, httpRes, err := apiClient.PlanetaryInteractionAPI.GetCharactersCharacterIdPlanets(context.Background(), characterId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PlanetaryInteractionAPIService GetCharactersCharacterIdPlanetsPlanetId", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var characterId int64
		var planetId int64

		resp, httpRes, err := apiClient.PlanetaryInteractionAPI.GetCharactersCharacterIdPlanetsPlanetId(context.Background(), characterId, planetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PlanetaryInteractionAPIService GetCorporationsCorporationIdCustomsOffices", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var corporationId int64

		resp, httpRes, err := apiClient.PlanetaryInteractionAPI.GetCorporationsCorporationIdCustomsOffices(context.Background(), corporationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PlanetaryInteractionAPIService GetUniverseSchematicsSchematicId", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var schematicId int64

		resp, httpRes, err := apiClient.PlanetaryInteractionAPI.GetUniverseSchematicsSchematicId(context.Background(), schematicId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
